name: Chrona
main: dev.chrona.plugin.ChronaPlugin
version: ${version}
api-version: '1.21.8'
depend: [ProtocolLib]
commands:
  wallet:
    description: Show your balance
    usage: /wallet
  pay:
      description: Pay another player
      usage: /pay <player> <amount>
  econ:
      description: Admin economy ops
      permission: chrona.admin
      usage: /econ <mint|burn> <player> <amount>
  minergive:
        description: Give Waterstrike to a miner
        permission: chrona.admin
        usage: /minergive
  npcpath:
    description: Records NPC paths
    usage: /npcpath
  npc:
    description: NPC management
    usage: /npc
  dialogue:
    description: Chrona dialogue system
    usage: /dialogue
    aliases: [ dlg ]
